spring:
  application:
    name: laundry-system
  datasource:
    url: jdbc:mysql://localhost:3306/laundry_system
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret-key: una_clave_super_secreta_y_segura_1234567890
  expiration-minutes: 3

flyway:
  enabled: true
  locations: classpath:db/migration